### PR TITLE
Fix call to getCellOnto() in chapter 6

### PR DESCRIPTION
**Pull request by js2264**

### CODE REVIEW

**Comment by LTLA** [comment]
Oops. This slipped under the radar; thanks for the fix. Can you just limit the PR to the `getOnto` change?

**Comment by js2264** [comment]
Done!

**Comment by PeteHaitch** [comment]
@LTLA Could you please port this to `RELEASE_3_18` because it looks like the same thing is breaking the builds there (https://bioconductor.org/checkResults/3.18/books-LATEST/SingleRBook/). Thanks!

**Comment by LTLA** [comment]
Done.

**Pull request merged**
